#4 Add += and -= operators on Counter API
automerge/automerge-swift-archived pull request #52
Opened 2022-06-23 13:44 UTC by kkostov

As proposed in #4, Extends the Counter API to enable increment and decrement of the counter's value using addition assignment and subtraction assignment operators e.g.

```swift
struct Schema: Codable, Equatable {
    var counter: Counter?
}

var doc1 = Document(Schema())
let _ = doc1.change {
    $0.counter?.set(3)
}

let _ = doc1.change {
    $0.counter -= 1
    XCTAssertEqual($0.counter?.get(), 2)
}

let _ = doc1.change {
    $0.counter += 1
    XCTAssertEqual($0.counter?.get(), 3)
}
```

2022-06-27 13:41 UTC, lightsprint09 requested changes
Looks fantastic. Thanks for bringing this up. If you split up the test cases I can merge it.

2022-06-27 13:41 UTC, lightsprint09 commented on Tests/Proxy+CounterTests.swift
> +    func testAssignmentExpressions() {
Can you pleas split this up into more isolated test cases.

2022-06-27 18:30 UTC, kkostov commented on Tests/Proxy+CounterTests.swift
> +    func testAssignmentExpressions() {
Thanks! Indeed it looks/reads much better as separate test cases.

2022-06-28 15:34 UTC, lightsprint09 approved these changes
Great. Thanks for splitting up the tests. Feel free to merge 👏🏾

2022-07-01 12:11 UTC, kkostov commented
Awesome! I don't actually have permission to merge it by myself 😇

2022-07-05 07:12 UTC, merged